default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: shirt-quote-backend_development

test:
  <<: *default
  database: shirt-quote-backend_test

production:
  <<: *default
  database: shirt-quote-backend_production
  username: shirt-quote-backend
  password: <%= ENV['SHIRT-QUOTE-BACKEND_DATABASE_PASSWORD'] %>
