#Champion Manufacture
champ = Manufacture.find_or_create_by(name: "Champion", logo: "https://www.alphabroder.com/images/alp/millMedium/38.jpg")
# Champion - Short Sleeve T-Shirt - T425
sstshirt = Style.find_or_create_by(name: "Champion - Short Sleeve T-Shirt - T425", front: "https://www.ssactivewear.com/Images/Color/30344_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30344_b_fl.jpg", starting_color: "Dark Green", size: "S, M, L, XL, 2XL, 3XL", gender: "Unisex", age_group: "Adult", category: "T-Shirt", manufacture_id: champ.id)
Color.find_or_create_by(name: "lightskyblue", front: "https://www.ssactivewear.com/Images/Color/30720_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30720_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Light Blue", style_id: sstshirt.id)
Color.find_or_create_by(name: "royalblue", front: "https://www.ssactivewear.com/Images/Color/30346_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30346_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Royal Blue", style_id: sstshirt.id)
Color.find_or_create_by(name: "navy", front: "https://www.ssactivewear.com/Images/Color/30345_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30345_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Navy", style_id: sstshirt.id)
Color.find_or_create_by(name: "snow", front: "https://www.ssactivewear.com/Images/Color/30354_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30354_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Ash", style_id: sstshirt.id)
Color.find_or_create_by(name: "red", front: "https://www.ssactivewear.com/Images/Color/30348_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30348_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Red", style_id: sstshirt.id)
Color.find_or_create_by(name: "maroon", front: "https://www.ssactivewear.com/Images/Color/30351_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30351_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Maroon", style_id: sstshirt.id)
Color.find_or_create_by(name: "silver", front: "https://www.ssactivewear.com/Images/Color/30347_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30347_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Light Steel", style_id: sstshirt.id)
Color.find_or_create_by(name: "dimgray", front: "https://www.ssactivewear.com/Images/Color/30352_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30352_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Charcoal Heather", style_id: sstshirt.id)
Color.find_or_create_by(name: "black", front: "https://www.ssactivewear.com/Images/Color/30342_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30342_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Black", style_id: sstshirt.id)
Color.find_or_create_by(name: "darkgreen", front: "https://www.ssactivewear.com/Images/Color/30344_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30344_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Dark Green", style_id: sstshirt.id)
Color.find_or_create_by(name: "white", front: "https://www.ssactivewear.com/Images/Color/30343_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30343_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White", style_id: sstshirt.id)
Color.find_or_create_by(name: "gold", front: "https://www.ssactivewear.com/Images/Color/30349_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30349_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Gold", style_id: sstshirt.id)
Color.find_or_create_by(name: "orange", front: "https://www.ssactivewear.com/Images/Color/30355_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30355_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Orange", style_id: sstshirt.id)
Color.find_or_create_by(name: "purple", front: "https://www.ssactivewear.com/Images/Color/30357_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30357_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Purple", style_id: sstshirt.id)
# Champion - Raglan Baseball T-Shirt - T137
raglan = Style.find_or_create_by(name: "Champion - Raglan Baseball T-Shirt - T137", front: "https://www.ssactivewear.com/Images/Color/33999_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33999_b_fl.jpg", starting_color: "Light Blue / Navy", size: "S, M, L, XL, 2XL, 3XL", gender: "Unisex", age_group: "Adult", category: "Raglan, T-Shirt", manufacture_id: champ.id)
Color.find_or_create_by(multi: true, name: "lightskyblue", name2: "navy", front: "https://www.ssactivewear.com/Images/Color/33999_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33999_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Light Blue / Navy", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "darkred", name2: "black", front: "https://www.ssactivewear.com/Images/Color/34004_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34004_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Scarlet / Black", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "darkred", front: "https://www.ssactivewear.com/Images/Color/34002_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34002_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Scarlet", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "blue", front: "https://www.ssactivewear.com/Images/Color/34003_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34003_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Team Blue", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "black", front: "https://www.ssactivewear.com/Images/Color/34000_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34000_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Black", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "navy", front: "https://www.ssactivewear.com/Images/Color/34001_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34001_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Navy", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "black", name2: "white", front: "https://www.ssactivewear.com/Images/Color/33997_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33997_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Black / White", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "black", front: "https://www.ssactivewear.com/Images/Color/33998_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33998_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Black", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "gold", front: "https://www.ssactivewear.com/Images/Color/34005_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34005_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Gold", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "darkgreen", front: "https://www.ssactivewear.com/Images/Color/34006_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34006_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Dark Green", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "maroon", front: "https://www.ssactivewear.com/Images/Color/34007_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34007_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Maroon", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "navy", front: "https://www.ssactivewear.com/Images/Color/34008_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34008_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Navy", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "darkred", front: "https://www.ssactivewear.com/Images/Color/34009_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34009_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Scarlet", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "white", name2: "blue", front: "https://www.ssactivewear.com/Images/Color/34010_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/34010_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "White / Team Blue", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "dimgray", front: "https://www.ssactivewear.com/Images/Color/51550_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/51550_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Charcoal Heather", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "gold", front: "https://www.ssactivewear.com/Images/Color/51553_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/51553_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Gold", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "pink", front: "https://www.ssactivewear.com/Images/Color/51551_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/51551_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Charity Pink", style_id: raglan.id)
Color.find_or_create_by(multi: true, name: "silver", name2: "purple", front: "https://www.ssactivewear.com/Images/Color/51552_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/51552_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL", actual_color: "Oxf Gray / Purple", style_id: raglan.id)
#Champion - Long Sleeve T-Shirt - CC8C
cc8c = Style.find_or_create_by(name: "Champion - Long Sleeve T-Shirt - CC8C", front: "https://www.ssactivewear.com/Images/Color/30339_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30339_b_fl.jpg", starting_color: "Royal Blue", size: "S, M, L, XL, 2XL", gender: "Unisex", age_group: "Adult", category: "Long Sleeve", manufacture_id: champ.id)
Color.find_or_create_by(name: "blue", front: "https://www.ssactivewear.com/Images/Color/30339_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30339_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "Royal Blue", style_id: cc8c.id)
Color.find_or_create_by(name: "red", front: "https://www.ssactivewear.com/Images/Color/30341_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30341_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "Red", style_id: cc8c.id)
Color.find_or_create_by(name: "navy", front: "https://www.ssactivewear.com/Images/Color/30338_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30338_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "Navy", style_id: cc8c.id)
Color.find_or_create_by(name: "silver", front: "https://www.ssactivewear.com/Images/Color/30340_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30340_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "Light Steel", style_id: cc8c.id)
Color.find_or_create_by(name: "black", front: "https://www.ssactivewear.com/Images/Color/30336_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30336_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "Black", style_id: cc8c.id)
Color.find_or_create_by(name: "white", front: "https://www.ssactivewear.com/Images/Color/30337_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30337_b_fl.jpg", size: "S, M, L, XL, 2XL", actual_color: "White", style_id: cc8c.id)
#Champion - Long Sleeve T-Shirt - CC8C
cc8c = Style.find_or_create_by(name: "Champion - Long Sleeve T-Shirt - CC8C", front: "https://www.ssactivewear.com/Images/Color/30339_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/30339_b_fl.jpg", starting_color: "Royal Blue", size: "S, M, L, XL, 2XL", gender: "Unisex", age_group: "Adult", category: "Long Sleeve", manufacture_id: champ.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Gildan Manufacture
gildan = Manufacture.find_or_create_by(name: "Gildan", logo: "https://www.alphabroder.com/images/alp/millMedium/07.jpg")
#Gildan - Softstyle T-Shirt - 64000
softstyle = Style.find_or_create_by(name: "Gildan - Softstyle T-Shirt - 64000", front: "https://www.ssactivewear.com/Images/Color/33310_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33310_b_fl.jpg", starting_color: "Antique Cherry Red", size: "S, M, L, XL, 2XL, 3XL, 4XL", gender: "Unisex", age_group: "Adult", category: "T-Shirt", manufacture_id: gildan.id)
Color.find_or_create_by(name: "crimson", front: "https://www.ssactivewear.com/Images/Color/33310_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33310_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Antique Cherry Red", style_id: softstyle.id)
Color.find_or_create_by(name: "white", front: "https://www.ssactivewear.com/Images/Color/29885_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/29885_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "White", style_id: softstyle.id)
Color.find_or_create_by(name: "black", front: "https://www.ssactivewear.com/Images/Color/29881_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/29881_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Black", style_id: softstyle.id)
Color.find_or_create_by(name: "fuchsia", front: "https://www.ssactivewear.com/Images/Color/37318_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/37318_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Antique Heliconia", style_id: softstyle.id)
Color.find_or_create_by(name: "mediumblue", front: "https://www.ssactivewear.com/Images/Color/33309_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/33309_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Antique Sapphire", style_id: softstyle.id)
Color.find_or_create_by(name: "lightpink", front: "https://www.ssactivewear.com/Images/Color/52348_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/52348_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Azalea", style_id: softstyle.id)
Color.find_or_create_by(name: "mediumvioletred", front: "https://www.ssactivewear.com/Images/Color/52350_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/52350_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Berry", style_id: softstyle.id)
Color.find_or_create_by(name: "darkslateblue", front: "https://www.ssactivewear.com/Images/Color/52351_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/52351_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Blackberry", style_id: softstyle.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Jerzees Manufacture
jerzees = Manufacture.find_or_create_by(name: "Jerzees", logo: "https://www.alphabroder.com/images/alp/millMedium/10.jpg")
#Jerzees - NuBlend Hooded Sweatshirt - 996MR
jznbhs = Style.find_or_create_by(name: "Jerzees - NuBlend Hooded Sweatshirt - 996MR", front: "https://www.ssactivewear.com/Images/Color/19723_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/19723_b_fl.jpg", starting_color: "White", size: "S, M, L, XL, 2XL, 3XL", gender: "Unisex", age_group: "Adult", category: "Sweatshirt", manufacture_id: jerzees.id)
Color.find_or_create_by(name: "white", front: "https://www.ssactivewear.com/Images/Color/19723_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/19723_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "White", style_id: jznbhs.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Next Level Manufacture
nla = Manufacture.find_or_create_by(name: "Next Level", logo: "https://www.alphabroder.com/images/alp/millMedium/nl.jpg")
#Next Level - Premium Fitted CVC Crew - 6210
nl6210 = Style.find_or_create_by(name: "Next Level - Premium Fitted CVC Crew - 6210", front: "https://www.ssactivewear.com/Images/Color/42895_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/42895_b_fl.jpg", starting_color: "Indigo", size: "S, M, L, XL, 2XL, 3XL, 4XL", gender: "Unisex", age_group: "Adult", category: "T-Shirt", manufacture_id: nla.id)
Color.find_or_create_by(name: "steelblue", front: "https://www.ssactivewear.com/Images/Color/42895_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/42895_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "Indigo", style_id: nl6210.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Comfort Colors Manufacture
comfcol = Manufacture.find_or_create_by(name: "Comfort Colors", logo:"https://www.alphabroder.com/images/alp/millMedium/cc.jpg")
#Comfort Colors - Garment Dyed Heavyweight Ringspun Tank Top - 9360
cc9360= Style.find_or_create_by(name: "Comfort Colors - Garment Dyed Heavyweight Ringspun Tank Top - 9360", front: "https://www.ssactivewear.com/Images/Color/35468_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/35468_b_fl.jpg", starting_color: "White", size: "S, M, L, XL, 2XL, 3XL, 4XL", gender: "Unisex", age_group: "Adult", category: "Tank Top", manufacture_id: comfcol.id)
Color.find_or_create_by(name: "white", front: "https://www.ssactivewear.com/Images/Color/35468_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/35468_b_fl.jpg", size: "S, M, L, XL, 2XL, 3XL, 4XL", actual_color: "White", style_id: cc9360.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Bella Canvas Manufacture
belcan = Manufacture.find_or_create_by(name: "Bella Canvas", logo:"")
#Bella Canvas - Women's Flowy Racerback Tank - 8800
bel8800 = Style.find_or_create_by(name: "Bella Canvas - Women's Flowy Racerback Tank - 8800", front: "https://www.ssactivewear.com/Images/Color/39812_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/39812_b_fl.jpg", starting_color: "Neon Pink", size: "S, M, L, XL, 2XL", gender: "Women", age_group: "Adult", category: "Tank Top", manufacture_id: belcan.id)
Color.find_or_create_by(name: "pink", front: "https://www.ssactivewear.com/Images/Color/39812_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/39812_b_fl.jpg", actual_color: "Neon Pink", size: "S, M, L, XL, 2XL", style_id: bel8800.id)
#-----------------------------------------------------------------------------------------------------------------------------
#Independent Manufacture
indep = Manufacture.find_or_create_by(name: "Independent", logo:"")
#Independent - Youth Midweight Hooded Pullover Sweatshirt - SS4001Y
inss4001y = Style.find_or_create_by(name: "Independent - Youth Midweight Hooded Pullover Sweatshirt - SS4001Y", front: "https://www.ssactivewear.com/Images/Color/44318_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/44318_b_fl.jpg", starting_color: "Red", size: "S, M, L, XL", gender: "Unisex", age_group: "Youth", category: "Sweatshirt", manufacture_id: indep.id)
Color.find_or_create_by(name: "red", front: "https://www.ssactivewear.com/Images/Color/44318_f_fl.jpg", back: "https://www.ssactivewear.com/Images/Color/44318_b_fl.jpg", actual_color: "Red", size: "S, M, L, XL", style_id: inss4001y.id)
